### ISSUE TITLE
Misc. todos

### ISSUE THREAD

**Issue by Casper-Guo** [Casper-Guo/Armchair-Strategist#75]
## December 2024
- [x] Revert #123 when new season schedule data becomes available (some updates to `app.py - set_event_options` needed to prevent `KeyError`) (#125)

## November 2024
- [x] ~Add a function for computing finishing order from the `Laps` dataframe as a backup to Ergast. Not sure how useful this will be once the Ergast replacement is up~
- [x] Bump Fastf1 version to 3.4.4 so we can get the complete 2024 season schedule data (otherwise rounds 1 to 9 are missing)

## August 2024
- [x] Simplify plotly code by removing `absolute_compound` argument from all APIs. This will also enable removing `season` argument from some plotting functions. (https://github.com/Casper-Guo/Armchair-Strategist/commit/8b6f41ee8600715d89794e2f898938f731398b20)
- [x] Standardize x-ticks across plots (https://github.com/Casper-Guo/Armchair-Strategist/commit/8b6f41ee8600715d89794e2f898938f731398b20)
- [x] ~Look at the callback graph and find optimizations. Can probably save some networking time if we skip some data reloads~
- [x] Use merging to calculate lap rep columns (https://github.com/Casper-Guo/Armchair-Strategist/commit/f31f99a6fe7c00e25429b941a0c8f998eb97d2ed)
- [x] Issue templates (#93)

## July 2024
- [x] Improve time zone handling in preprocessing (#77)
- [x] Dash app get session list based on what's available in data (#77)
- [x] Bash scripts suppress expect scripts non-error output (https://github.com/Casper-Guo/Armchair-Strategist/commit/727cab07a9218cd3a93f660776d4967516bce4aa)
- [x] All plotting functions and `get_driver` support `drivers=None` to include all drivers (#83)
- [x] Put dashboard static layouts in a separate file (#80)
- [x] Use [`prevent_initial_call`](https://dash.plotly.com/advanced-callbacks#prevent-callback-execution-upon-initial-component-render) to simplify callbacks that need special handling on initial page loading (#81)
- [x] Look into other incorporating other advanced callback usages, especially `running`
- [x] Look into using [orjson](https://dash.plotly.com/performance#data-serialization) and other [performance tips](https://dash.plotly.com/performance). (https://github.com/Casper-Guo/Armchair-Strategist/commit/87ea62ea9df4e76123d1ac422168093ccd5d1575)
