### ISSUE TITLE
Future code improvement goals

### ISSUE THREAD

**Issue by Casper-Guo** [Casper-Guo/Armchair-Strategist#9]
- [x] Better style checks with either pre-commit or Github Actions (flake8, pydocstyle etc.)
- [x] ~~Unit tests~~ (relying on reconciliation with previous data/visualization is more suitable)
- [x] Standardize import order, enforce with isort or similar
- [x] Shell script / Git actions for automatic ETL every Monday (#17)
- [x] Deprecate data loading and data processing notebooks (#32)
- [x] More unified approach to filtering laps for visualization (#76)
- [x] ~~Release as a package~~

**Comment by Casper-Guo** [comment]
Releasing as a package is no longer a priority. The primary goal of the visualization functions are to support the website.
